apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fw4le3v4a-java-quarkus
  janus-idp.io/tekton: fw4le3v4a-java-quarkus
  backstage.io/kubernetes-id: fw4le3v4a-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fw4le3v4a-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
